### PR TITLE
Clean up repository, keep only DPM related code

### PR DESCRIPTION
**Pull request by phoracek**
This change updates vendoring, drops everything but DPM and fixes documentation.

### CODE REVIEW

**Comment by phoracek** [comment]
There is one possible problem. Since both DPM and DP implementation using it import pluginapi there could be a dependency failure (each uses different version). It should be OK when vendoring is used though.

**Comment by mpolednik** [comment]
The overall problem is the fact that pluginapi itself is not stable yet - so even vendoring doesn't help. We can't help that - device plugins first need to mature within k8s.

**Comment by phoracek** [comment]
Agree. But without vendoring, I'm afraid, we cannot even compile. However, I think it is a sane requirement.

**Comment by mpolednik** [comment]
What I meant is that vendoring is necessary yet insufficient tool for pluginapi API stability.

**Review by mpolednik — APPROVED** [review]

**Pull request merged**
