### PR TITLE
Bump to Kubernetes 1.19

### PR DESCRIPTION
**Pull request by rhrazdil**
Updating dependencies.

Added `GetPreferredAllocation` function for `FakeDevicePlugin`.
This is required for kubevirt/macvtap-cni to move to k8s.io/kubelet version v0.19.z.

### CODE REVIEW

**Comment by rhrazdil** [comment]
@phoracek

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Comment by phoracek** [comment]
@rhrazdil we don't have a great test coverage in this project. Would you please try this change on the macvtap repository (`replace` this repo with your fork) and see if it works?

**Comment by rhrazdil** [comment]
@phoracek I have verified that macvtap e2e tests and unit test pass with this change.
the `GetPreferredAllocation` will need to be defined in macvtap-cni repo as well

**Comment by phoracek** [comment]
Thanks. Merging this and releasing a new version.

**Pull request merged**
