### PR TITLE
Fix registration order k8s 1.25

### PR DESCRIPTION
**Pull request by maiqueb**

### CODE REVIEW

**Comment by cgwalters** [comment]
OK so we currently have a fork of a really old version of this kvm device plugin for CI purposes, see https://github.com/cgwalters/kvm-device-plugin

We upgraded the OpenShift build02 cluster to a 4.12 candidate build, and our plugin started failing.

I then discovered this change and I read https://github.com/kubernetes/kubernetes/issues/112395 etc.  And...I find myself really confused because actually, isn't this change the exact *opposite* of what's necessary?

I have a cluster
```
[root@jupiter ~]# oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.nightly-2022-10-18-041406   True        False         20h     Cluster version is 4.12.0-0.nightly-2022-10-18-041406
[root@jupiter ~]# oc version | grep Kubernetes
Kubernetes Version: v1.25.2+5bf2e1f
[root@jupiter ~]#
```

And from reading the change, and actually trying this out:
https://github.com/cgwalters/kvm-device-plugin/commit/17c86040335a9a7435eba237cf0e106fc0f51613

We need to be serving our GRPC socket *before* registering right?

**Comment by maiqueb** [comment]
> OK so we currently have a fork of a really old version of this kvm device plugin for CI purposes, see https://github.com/cgwalters/kvm-device-plugin
> 
> We upgraded the OpenShift build02 cluster to a 4.12 candidate build, and our plugin started failing.
> 
> I then discovered this change and I read [kubernetes/kubernetes#112395](https://github.com/kubernetes/kubernetes/issues/112395) etc. And...I find myself really confused because actually, isn't this change the exact _opposite_ of what's necessary?
> 
> I have a cluster
> 
> ```
> [root@jupiter ~]# oc get clusterversion
> NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
> version   4.12.0-0.nightly-2022-10-18-041406   True        False         20h     Cluster version is 4.12.0-0.nightly-2022-10-18-041406
> [root@jupiter ~]# oc version | grep Kubernetes
> Kubernetes Version: v1.25.2+5bf2e1f
> [root@jupiter ~]#
> ```
> 
> And from reading the change, and actually trying this out: [cgwalters/kvm-device-plugin@17c8604](https://github.com/cgwalters/kvm-device-plugin/commit/17c86040335a9a7435eba237cf0e106fc0f51613)
> 
> We need to be serving our GRPC socket _before_ registering right?

hey @cgwalters ; how is your proposal different from what we had before the change in this PR ? It could be I messed this up, and for some reason this flew under the radar for this long.

At the same, let's try to agree on what is the correct behavior - afaiu, we need to *first* serve, *then* register:
> The new semantics are similar, except that no go-routine is launched to connect to the gRPC service. The connection is attempted synchronously. **This means that the plugin must now start serving its gRPC server before registering itself with the kubelet. Otherwise the registration call will fail. **

... thus it seems you're right and I've messed this up. 

Did you confirm your fix actually fixed the device plugin registration for 4.12 ? If so, we can revert this.

**Comment by cgwalters** [comment]
> Did you confirm your fix actually fixed the device plugin registration for 4.12 ? If so, we can revert this.

Yes, reverting it made things work.

**Comment by maiqueb** [comment]
Thanks for the reply. Let me confirm one thing before the revert; I'll keep you posted.

**Pull request merged**
